version: 0.2
phases:
  install:
    runtime-versions:
      java: corretto17
  build:
    commands:
      - mvn clean install
      - mv target/*.war app.war
artifacts:
  files:
    - app.war
  discard-paths: yes
#artifacts:
#  files:
#    - target/*.war
#  discard-paths: yes